//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.3038。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WSWSYofotoFacadeSoapBinding", Namespace="http://172.16.18.212:7888/ormrpc/services/WSWSYofotoFacade")]
public partial class WSWSYofotoFacadeSrvProxyService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public WSWSYofotoFacadeSrvProxyService() {
        this.Url = "http://172.16.18.212:7888/ormrpc/services/WSWSYofotoFacade";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://webservice.yofoto.eas.kingdee.com", ResponseNamespace="http://172.16.18.212:7888/ormrpc/services/WSWSYofotoFacade")]
    [return: System.Xml.Serialization.SoapElementAttribute("deleteSaleOrderByNumberReturn")]
    public string deleteSaleOrderByNumber(string xmlData) {
        object[] results = this.Invoke("deleteSaleOrderByNumber", new object[] {
                    xmlData});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindeleteSaleOrderByNumber(string xmlData, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("deleteSaleOrderByNumber", new object[] {
                    xmlData}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EnddeleteSaleOrderByNumber(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://webservice.yofoto.eas.kingdee.com", ResponseNamespace="http://172.16.18.212:7888/ormrpc/services/WSWSYofotoFacade")]
    [return: System.Xml.Serialization.SoapElementAttribute("auditSaleIssueBillReturn")]
    public string auditSaleIssueBill(string orgNumber, string billNumber) {
        object[] results = this.Invoke("auditSaleIssueBill", new object[] {
                    orgNumber,
                    billNumber});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginauditSaleIssueBill(string orgNumber, string billNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("auditSaleIssueBill", new object[] {
                    orgNumber,
                    billNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndauditSaleIssueBill(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://webservice.yofoto.eas.kingdee.com", ResponseNamespace="http://172.16.18.212:7888/ormrpc/services/WSWSYofotoFacade")]
    [return: System.Xml.Serialization.SoapElementAttribute("getInventoryByStringReturn")]
    public string getInventoryByString(string OrgNumber, string WarehouseNumber, string materialNumber) {
        object[] results = this.Invoke("getInventoryByString", new object[] {
                    OrgNumber,
                    WarehouseNumber,
                    materialNumber});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetInventoryByString(string OrgNumber, string WarehouseNumber, string materialNumber, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getInventoryByString", new object[] {
                    OrgNumber,
                    WarehouseNumber,
                    materialNumber}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndgetInventoryByString(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
}
