//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace JWMSY.OrderService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WMSSoap", Namespace="http://tempuri.org/")]
    public partial class WMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBatchRunnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductDetail1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductDetail2OperationCompleted;
        
        private System.Threading.SendOrPostCallback IsExistsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WMS() {
            this.Url = global::JWMSY.Properties.Settings.Default.JWMSY_OrderService_WMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBatchRunnoCompletedEventHandler GetBatchRunnoCompleted;
        
        /// <remarks/>
        public event GetProductDetail1CompletedEventHandler GetProductDetail1Completed;
        
        /// <remarks/>
        public event GetProductDetail2CompletedEventHandler GetProductDetail2Completed;
        
        /// <remarks/>
        public event IsExistsCompletedEventHandler IsExistsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBatchRunno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBatchRunno(string batchNo, string keys) {
            object[] results = this.Invoke("GetBatchRunno", new object[] {
                        batchNo,
                        keys});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBatchRunnoAsync(string batchNo, string keys) {
            this.GetBatchRunnoAsync(batchNo, keys, null);
        }
        
        /// <remarks/>
        public void GetBatchRunnoAsync(string batchNo, string keys, object userState) {
            if ((this.GetBatchRunnoOperationCompleted == null)) {
                this.GetBatchRunnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBatchRunnoOperationCompleted);
            }
            this.InvokeAsync("GetBatchRunno", new object[] {
                        batchNo,
                        keys}, this.GetBatchRunnoOperationCompleted, userState);
        }
        
        private void OnGetBatchRunnoOperationCompleted(object arg) {
            if ((this.GetBatchRunnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBatchRunnoCompleted(this, new GetBatchRunnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductDetail1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetProductDetail1(string batchNo, string keys) {
            object[] results = this.Invoke("GetProductDetail1", new object[] {
                        batchNo,
                        keys});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductDetail1Async(string batchNo, string keys) {
            this.GetProductDetail1Async(batchNo, keys, null);
        }
        
        /// <remarks/>
        public void GetProductDetail1Async(string batchNo, string keys, object userState) {
            if ((this.GetProductDetail1OperationCompleted == null)) {
                this.GetProductDetail1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductDetail1OperationCompleted);
            }
            this.InvokeAsync("GetProductDetail1", new object[] {
                        batchNo,
                        keys}, this.GetProductDetail1OperationCompleted, userState);
        }
        
        private void OnGetProductDetail1OperationCompleted(object arg) {
            if ((this.GetProductDetail1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductDetail1Completed(this, new GetProductDetail1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProductDetail2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetProductDetail2(string ckNo, string keys) {
            object[] results = this.Invoke("GetProductDetail2", new object[] {
                        ckNo,
                        keys});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductDetail2Async(string ckNo, string keys) {
            this.GetProductDetail2Async(ckNo, keys, null);
        }
        
        /// <remarks/>
        public void GetProductDetail2Async(string ckNo, string keys, object userState) {
            if ((this.GetProductDetail2OperationCompleted == null)) {
                this.GetProductDetail2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductDetail2OperationCompleted);
            }
            this.InvokeAsync("GetProductDetail2", new object[] {
                        ckNo,
                        keys}, this.GetProductDetail2OperationCompleted, userState);
        }
        
        private void OnGetProductDetail2OperationCompleted(object arg) {
            if ((this.GetProductDetail2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductDetail2Completed(this, new GetProductDetail2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsExists", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int IsExists(string ckno, string keys) {
            object[] results = this.Invoke("IsExists", new object[] {
                        ckno,
                        keys});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void IsExistsAsync(string ckno, string keys) {
            this.IsExistsAsync(ckno, keys, null);
        }
        
        /// <remarks/>
        public void IsExistsAsync(string ckno, string keys, object userState) {
            if ((this.IsExistsOperationCompleted == null)) {
                this.IsExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsExistsOperationCompleted);
            }
            this.InvokeAsync("IsExists", new object[] {
                        ckno,
                        keys}, this.IsExistsOperationCompleted, userState);
        }
        
        private void OnIsExistsOperationCompleted(object arg) {
            if ((this.IsExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsExistsCompleted(this, new IsExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetBatchRunnoCompletedEventHandler(object sender, GetBatchRunnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBatchRunnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBatchRunnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetProductDetail1CompletedEventHandler(object sender, GetProductDetail1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductDetail1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductDetail1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetProductDetail2CompletedEventHandler(object sender, GetProductDetail2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductDetail2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductDetail2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void IsExistsCompletedEventHandler(object sender, IsExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591