//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace JWMSY.EasOrderService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EasOrderSoap", Namespace="http://www.kingdee.com/")]
    public partial class EasOrder : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPo2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPoDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransfer2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransferOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransferDelivery2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransferDeliveryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransferDeliveryDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransferDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOem2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOemDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWo2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWoDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProduce2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProduceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProduceDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSale2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSaleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSaleDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMaterialListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSemiOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EasOrder() {
            this.Url = global::JWMSY.Properties.Settings.Default.JWMSY_EasOrderService_EasOrder;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPo2CompletedEventHandler GetPo2Completed;
        
        /// <remarks/>
        public event GetPoCompletedEventHandler GetPoCompleted;
        
        /// <remarks/>
        public event GetPoDetailCompletedEventHandler GetPoDetailCompleted;
        
        /// <remarks/>
        public event GetTransfer2CompletedEventHandler GetTransfer2Completed;
        
        /// <remarks/>
        public event GetTransferCompletedEventHandler GetTransferCompleted;
        
        /// <remarks/>
        public event GetTransferDelivery2CompletedEventHandler GetTransferDelivery2Completed;
        
        /// <remarks/>
        public event GetTransferDeliveryCompletedEventHandler GetTransferDeliveryCompleted;
        
        /// <remarks/>
        public event GetTransferDeliveryDetailCompletedEventHandler GetTransferDeliveryDetailCompleted;
        
        /// <remarks/>
        public event GetTransferDetailCompletedEventHandler GetTransferDetailCompleted;
        
        /// <remarks/>
        public event GetOem2CompletedEventHandler GetOem2Completed;
        
        /// <remarks/>
        public event GetOemCompletedEventHandler GetOemCompleted;
        
        /// <remarks/>
        public event GetOemDetailCompletedEventHandler GetOemDetailCompleted;
        
        /// <remarks/>
        public event GetWo2CompletedEventHandler GetWo2Completed;
        
        /// <remarks/>
        public event GetWoCompletedEventHandler GetWoCompleted;
        
        /// <remarks/>
        public event GetWoDetailCompletedEventHandler GetWoDetailCompleted;
        
        /// <remarks/>
        public event GetProduce2CompletedEventHandler GetProduce2Completed;
        
        /// <remarks/>
        public event GetProduceCompletedEventHandler GetProduceCompleted;
        
        /// <remarks/>
        public event GetProduceDetailCompletedEventHandler GetProduceDetailCompleted;
        
        /// <remarks/>
        public event GetSale2CompletedEventHandler GetSale2Completed;
        
        /// <remarks/>
        public event GetSaleCompletedEventHandler GetSaleCompleted;
        
        /// <remarks/>
        public event GetSaleDetailCompletedEventHandler GetSaleDetailCompleted;
        
        /// <remarks/>
        public event GetMaterialListCompletedEventHandler GetMaterialListCompleted;
        
        /// <remarks/>
        public event GetRmCompletedEventHandler GetRmCompleted;
        
        /// <remarks/>
        public event GetSemiCompletedEventHandler GetSemiCompleted;
        
        /// <remarks/>
        public event GetProCompletedEventHandler GetProCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetPo2", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPo2(string cOrderNumber) {
            object[] results = this.Invoke("GetPo2", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPo2Async(string cOrderNumber) {
            this.GetPo2Async(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetPo2Async(string cOrderNumber, object userState) {
            if ((this.GetPo2OperationCompleted == null)) {
                this.GetPo2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPo2OperationCompleted);
            }
            this.InvokeAsync("GetPo2", new object[] {
                        cOrderNumber}, this.GetPo2OperationCompleted, userState);
        }
        
        private void OnGetPo2OperationCompleted(object arg) {
            if ((this.GetPo2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPo2Completed(this, new GetPo2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetPo", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPo() {
            object[] results = this.Invoke("GetPo", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPoAsync() {
            this.GetPoAsync(null);
        }
        
        /// <remarks/>
        public void GetPoAsync(object userState) {
            if ((this.GetPoOperationCompleted == null)) {
                this.GetPoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPoOperationCompleted);
            }
            this.InvokeAsync("GetPo", new object[0], this.GetPoOperationCompleted, userState);
        }
        
        private void OnGetPoOperationCompleted(object arg) {
            if ((this.GetPoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPoCompleted(this, new GetPoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetPoDetail", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPoDetail(string cOrderNumber) {
            object[] results = this.Invoke("GetPoDetail", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPoDetailAsync(string cOrderNumber) {
            this.GetPoDetailAsync(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetPoDetailAsync(string cOrderNumber, object userState) {
            if ((this.GetPoDetailOperationCompleted == null)) {
                this.GetPoDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPoDetailOperationCompleted);
            }
            this.InvokeAsync("GetPoDetail", new object[] {
                        cOrderNumber}, this.GetPoDetailOperationCompleted, userState);
        }
        
        private void OnGetPoDetailOperationCompleted(object arg) {
            if ((this.GetPoDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPoDetailCompleted(this, new GetPoDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetTransfer2", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTransfer2(string cOrderNumber) {
            object[] results = this.Invoke("GetTransfer2", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransfer2Async(string cOrderNumber) {
            this.GetTransfer2Async(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetTransfer2Async(string cOrderNumber, object userState) {
            if ((this.GetTransfer2OperationCompleted == null)) {
                this.GetTransfer2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransfer2OperationCompleted);
            }
            this.InvokeAsync("GetTransfer2", new object[] {
                        cOrderNumber}, this.GetTransfer2OperationCompleted, userState);
        }
        
        private void OnGetTransfer2OperationCompleted(object arg) {
            if ((this.GetTransfer2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransfer2Completed(this, new GetTransfer2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetTransfer", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTransfer() {
            object[] results = this.Invoke("GetTransfer", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransferAsync() {
            this.GetTransferAsync(null);
        }
        
        /// <remarks/>
        public void GetTransferAsync(object userState) {
            if ((this.GetTransferOperationCompleted == null)) {
                this.GetTransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransferOperationCompleted);
            }
            this.InvokeAsync("GetTransfer", new object[0], this.GetTransferOperationCompleted, userState);
        }
        
        private void OnGetTransferOperationCompleted(object arg) {
            if ((this.GetTransferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransferCompleted(this, new GetTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetTransferDelivery2", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTransferDelivery2(string cOrderNumber) {
            object[] results = this.Invoke("GetTransferDelivery2", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransferDelivery2Async(string cOrderNumber) {
            this.GetTransferDelivery2Async(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetTransferDelivery2Async(string cOrderNumber, object userState) {
            if ((this.GetTransferDelivery2OperationCompleted == null)) {
                this.GetTransferDelivery2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransferDelivery2OperationCompleted);
            }
            this.InvokeAsync("GetTransferDelivery2", new object[] {
                        cOrderNumber}, this.GetTransferDelivery2OperationCompleted, userState);
        }
        
        private void OnGetTransferDelivery2OperationCompleted(object arg) {
            if ((this.GetTransferDelivery2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransferDelivery2Completed(this, new GetTransferDelivery2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetTransferDelivery", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTransferDelivery() {
            object[] results = this.Invoke("GetTransferDelivery", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransferDeliveryAsync() {
            this.GetTransferDeliveryAsync(null);
        }
        
        /// <remarks/>
        public void GetTransferDeliveryAsync(object userState) {
            if ((this.GetTransferDeliveryOperationCompleted == null)) {
                this.GetTransferDeliveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransferDeliveryOperationCompleted);
            }
            this.InvokeAsync("GetTransferDelivery", new object[0], this.GetTransferDeliveryOperationCompleted, userState);
        }
        
        private void OnGetTransferDeliveryOperationCompleted(object arg) {
            if ((this.GetTransferDeliveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransferDeliveryCompleted(this, new GetTransferDeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetTransferDeliveryDetail", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTransferDeliveryDetail(string cOrderNumber) {
            object[] results = this.Invoke("GetTransferDeliveryDetail", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransferDeliveryDetailAsync(string cOrderNumber) {
            this.GetTransferDeliveryDetailAsync(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetTransferDeliveryDetailAsync(string cOrderNumber, object userState) {
            if ((this.GetTransferDeliveryDetailOperationCompleted == null)) {
                this.GetTransferDeliveryDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransferDeliveryDetailOperationCompleted);
            }
            this.InvokeAsync("GetTransferDeliveryDetail", new object[] {
                        cOrderNumber}, this.GetTransferDeliveryDetailOperationCompleted, userState);
        }
        
        private void OnGetTransferDeliveryDetailOperationCompleted(object arg) {
            if ((this.GetTransferDeliveryDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransferDeliveryDetailCompleted(this, new GetTransferDeliveryDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetTransferDetail", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTransferDetail(string cOrderNumber) {
            object[] results = this.Invoke("GetTransferDetail", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransferDetailAsync(string cOrderNumber) {
            this.GetTransferDetailAsync(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetTransferDetailAsync(string cOrderNumber, object userState) {
            if ((this.GetTransferDetailOperationCompleted == null)) {
                this.GetTransferDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransferDetailOperationCompleted);
            }
            this.InvokeAsync("GetTransferDetail", new object[] {
                        cOrderNumber}, this.GetTransferDetailOperationCompleted, userState);
        }
        
        private void OnGetTransferDetailOperationCompleted(object arg) {
            if ((this.GetTransferDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransferDetailCompleted(this, new GetTransferDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetOem2", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOem2(string cOrderNumber) {
            object[] results = this.Invoke("GetOem2", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOem2Async(string cOrderNumber) {
            this.GetOem2Async(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetOem2Async(string cOrderNumber, object userState) {
            if ((this.GetOem2OperationCompleted == null)) {
                this.GetOem2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOem2OperationCompleted);
            }
            this.InvokeAsync("GetOem2", new object[] {
                        cOrderNumber}, this.GetOem2OperationCompleted, userState);
        }
        
        private void OnGetOem2OperationCompleted(object arg) {
            if ((this.GetOem2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOem2Completed(this, new GetOem2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetOem", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOem() {
            object[] results = this.Invoke("GetOem", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOemAsync() {
            this.GetOemAsync(null);
        }
        
        /// <remarks/>
        public void GetOemAsync(object userState) {
            if ((this.GetOemOperationCompleted == null)) {
                this.GetOemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOemOperationCompleted);
            }
            this.InvokeAsync("GetOem", new object[0], this.GetOemOperationCompleted, userState);
        }
        
        private void OnGetOemOperationCompleted(object arg) {
            if ((this.GetOemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOemCompleted(this, new GetOemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetOemDetail", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetOemDetail(string cOrderNumber) {
            object[] results = this.Invoke("GetOemDetail", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetOemDetailAsync(string cOrderNumber) {
            this.GetOemDetailAsync(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetOemDetailAsync(string cOrderNumber, object userState) {
            if ((this.GetOemDetailOperationCompleted == null)) {
                this.GetOemDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOemDetailOperationCompleted);
            }
            this.InvokeAsync("GetOemDetail", new object[] {
                        cOrderNumber}, this.GetOemDetailOperationCompleted, userState);
        }
        
        private void OnGetOemDetailOperationCompleted(object arg) {
            if ((this.GetOemDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOemDetailCompleted(this, new GetOemDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetWo2", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetWo2(string cOrderNumber) {
            object[] results = this.Invoke("GetWo2", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetWo2Async(string cOrderNumber) {
            this.GetWo2Async(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetWo2Async(string cOrderNumber, object userState) {
            if ((this.GetWo2OperationCompleted == null)) {
                this.GetWo2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWo2OperationCompleted);
            }
            this.InvokeAsync("GetWo2", new object[] {
                        cOrderNumber}, this.GetWo2OperationCompleted, userState);
        }
        
        private void OnGetWo2OperationCompleted(object arg) {
            if ((this.GetWo2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWo2Completed(this, new GetWo2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetWo", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetWo() {
            object[] results = this.Invoke("GetWo", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetWoAsync() {
            this.GetWoAsync(null);
        }
        
        /// <remarks/>
        public void GetWoAsync(object userState) {
            if ((this.GetWoOperationCompleted == null)) {
                this.GetWoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWoOperationCompleted);
            }
            this.InvokeAsync("GetWo", new object[0], this.GetWoOperationCompleted, userState);
        }
        
        private void OnGetWoOperationCompleted(object arg) {
            if ((this.GetWoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWoCompleted(this, new GetWoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetWoDetail", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetWoDetail(string cOrderNumber) {
            object[] results = this.Invoke("GetWoDetail", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetWoDetailAsync(string cOrderNumber) {
            this.GetWoDetailAsync(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetWoDetailAsync(string cOrderNumber, object userState) {
            if ((this.GetWoDetailOperationCompleted == null)) {
                this.GetWoDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWoDetailOperationCompleted);
            }
            this.InvokeAsync("GetWoDetail", new object[] {
                        cOrderNumber}, this.GetWoDetailOperationCompleted, userState);
        }
        
        private void OnGetWoDetailOperationCompleted(object arg) {
            if ((this.GetWoDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWoDetailCompleted(this, new GetWoDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetProduce2", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetProduce2(string cOrderNumber) {
            object[] results = this.Invoke("GetProduce2", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetProduce2Async(string cOrderNumber) {
            this.GetProduce2Async(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetProduce2Async(string cOrderNumber, object userState) {
            if ((this.GetProduce2OperationCompleted == null)) {
                this.GetProduce2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProduce2OperationCompleted);
            }
            this.InvokeAsync("GetProduce2", new object[] {
                        cOrderNumber}, this.GetProduce2OperationCompleted, userState);
        }
        
        private void OnGetProduce2OperationCompleted(object arg) {
            if ((this.GetProduce2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProduce2Completed(this, new GetProduce2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetProduce", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetProduce() {
            object[] results = this.Invoke("GetProduce", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetProduceAsync() {
            this.GetProduceAsync(null);
        }
        
        /// <remarks/>
        public void GetProduceAsync(object userState) {
            if ((this.GetProduceOperationCompleted == null)) {
                this.GetProduceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProduceOperationCompleted);
            }
            this.InvokeAsync("GetProduce", new object[0], this.GetProduceOperationCompleted, userState);
        }
        
        private void OnGetProduceOperationCompleted(object arg) {
            if ((this.GetProduceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProduceCompleted(this, new GetProduceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetProduceDetail", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetProduceDetail(string cOrderNumber) {
            object[] results = this.Invoke("GetProduceDetail", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetProduceDetailAsync(string cOrderNumber) {
            this.GetProduceDetailAsync(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetProduceDetailAsync(string cOrderNumber, object userState) {
            if ((this.GetProduceDetailOperationCompleted == null)) {
                this.GetProduceDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProduceDetailOperationCompleted);
            }
            this.InvokeAsync("GetProduceDetail", new object[] {
                        cOrderNumber}, this.GetProduceDetailOperationCompleted, userState);
        }
        
        private void OnGetProduceDetailOperationCompleted(object arg) {
            if ((this.GetProduceDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProduceDetailCompleted(this, new GetProduceDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetSale2", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSale2(string cOrderNumber) {
            object[] results = this.Invoke("GetSale2", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSale2Async(string cOrderNumber) {
            this.GetSale2Async(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetSale2Async(string cOrderNumber, object userState) {
            if ((this.GetSale2OperationCompleted == null)) {
                this.GetSale2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSale2OperationCompleted);
            }
            this.InvokeAsync("GetSale2", new object[] {
                        cOrderNumber}, this.GetSale2OperationCompleted, userState);
        }
        
        private void OnGetSale2OperationCompleted(object arg) {
            if ((this.GetSale2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSale2Completed(this, new GetSale2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetSale", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSale() {
            object[] results = this.Invoke("GetSale", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSaleAsync() {
            this.GetSaleAsync(null);
        }
        
        /// <remarks/>
        public void GetSaleAsync(object userState) {
            if ((this.GetSaleOperationCompleted == null)) {
                this.GetSaleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSaleOperationCompleted);
            }
            this.InvokeAsync("GetSale", new object[0], this.GetSaleOperationCompleted, userState);
        }
        
        private void OnGetSaleOperationCompleted(object arg) {
            if ((this.GetSaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSaleCompleted(this, new GetSaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetSaleDetail", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSaleDetail(string cOrderNumber) {
            object[] results = this.Invoke("GetSaleDetail", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSaleDetailAsync(string cOrderNumber) {
            this.GetSaleDetailAsync(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetSaleDetailAsync(string cOrderNumber, object userState) {
            if ((this.GetSaleDetailOperationCompleted == null)) {
                this.GetSaleDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSaleDetailOperationCompleted);
            }
            this.InvokeAsync("GetSaleDetail", new object[] {
                        cOrderNumber}, this.GetSaleDetailOperationCompleted, userState);
        }
        
        private void OnGetSaleDetailOperationCompleted(object arg) {
            if ((this.GetSaleDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSaleDetailCompleted(this, new GetSaleDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetMaterialList", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMaterialList(string cOrderNumber) {
            object[] results = this.Invoke("GetMaterialList", new object[] {
                        cOrderNumber});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMaterialListAsync(string cOrderNumber) {
            this.GetMaterialListAsync(cOrderNumber, null);
        }
        
        /// <remarks/>
        public void GetMaterialListAsync(string cOrderNumber, object userState) {
            if ((this.GetMaterialListOperationCompleted == null)) {
                this.GetMaterialListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMaterialListOperationCompleted);
            }
            this.InvokeAsync("GetMaterialList", new object[] {
                        cOrderNumber}, this.GetMaterialListOperationCompleted, userState);
        }
        
        private void OnGetMaterialListOperationCompleted(object arg) {
            if ((this.GetMaterialListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMaterialListCompleted(this, new GetMaterialListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetRm", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetRm() {
            object[] results = this.Invoke("GetRm", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetRmAsync() {
            this.GetRmAsync(null);
        }
        
        /// <remarks/>
        public void GetRmAsync(object userState) {
            if ((this.GetRmOperationCompleted == null)) {
                this.GetRmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRmOperationCompleted);
            }
            this.InvokeAsync("GetRm", new object[0], this.GetRmOperationCompleted, userState);
        }
        
        private void OnGetRmOperationCompleted(object arg) {
            if ((this.GetRmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRmCompleted(this, new GetRmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetSemi", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSemi() {
            object[] results = this.Invoke("GetSemi", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSemiAsync() {
            this.GetSemiAsync(null);
        }
        
        /// <remarks/>
        public void GetSemiAsync(object userState) {
            if ((this.GetSemiOperationCompleted == null)) {
                this.GetSemiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSemiOperationCompleted);
            }
            this.InvokeAsync("GetSemi", new object[0], this.GetSemiOperationCompleted, userState);
        }
        
        private void OnGetSemiOperationCompleted(object arg) {
            if ((this.GetSemiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSemiCompleted(this, new GetSemiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kingdee.com/GetPro", RequestNamespace="http://www.kingdee.com/", ResponseNamespace="http://www.kingdee.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPro() {
            object[] results = this.Invoke("GetPro", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetProAsync() {
            this.GetProAsync(null);
        }
        
        /// <remarks/>
        public void GetProAsync(object userState) {
            if ((this.GetProOperationCompleted == null)) {
                this.GetProOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProOperationCompleted);
            }
            this.InvokeAsync("GetPro", new object[0], this.GetProOperationCompleted, userState);
        }
        
        private void OnGetProOperationCompleted(object arg) {
            if ((this.GetProCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProCompleted(this, new GetProCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPo2CompletedEventHandler(object sender, GetPo2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPo2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPo2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPoCompletedEventHandler(object sender, GetPoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPoDetailCompletedEventHandler(object sender, GetPoDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPoDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPoDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTransfer2CompletedEventHandler(object sender, GetTransfer2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransfer2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransfer2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTransferCompletedEventHandler(object sender, GetTransferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTransferDelivery2CompletedEventHandler(object sender, GetTransferDelivery2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransferDelivery2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransferDelivery2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTransferDeliveryCompletedEventHandler(object sender, GetTransferDeliveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransferDeliveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransferDeliveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTransferDeliveryDetailCompletedEventHandler(object sender, GetTransferDeliveryDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransferDeliveryDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransferDeliveryDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTransferDetailCompletedEventHandler(object sender, GetTransferDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransferDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransferDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetOem2CompletedEventHandler(object sender, GetOem2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOem2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOem2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetOemCompletedEventHandler(object sender, GetOemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetOemDetailCompletedEventHandler(object sender, GetOemDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOemDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOemDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetWo2CompletedEventHandler(object sender, GetWo2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWo2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWo2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetWoCompletedEventHandler(object sender, GetWoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetWoDetailCompletedEventHandler(object sender, GetWoDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWoDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWoDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetProduce2CompletedEventHandler(object sender, GetProduce2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProduce2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProduce2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetProduceCompletedEventHandler(object sender, GetProduceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProduceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProduceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetProduceDetailCompletedEventHandler(object sender, GetProduceDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProduceDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProduceDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSale2CompletedEventHandler(object sender, GetSale2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSale2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSale2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSaleCompletedEventHandler(object sender, GetSaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSaleDetailCompletedEventHandler(object sender, GetSaleDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSaleDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSaleDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMaterialListCompletedEventHandler(object sender, GetMaterialListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMaterialListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMaterialListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRmCompletedEventHandler(object sender, GetRmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSemiCompletedEventHandler(object sender, GetSemiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSemiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSemiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetProCompletedEventHandler(object sender, GetProCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591