//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace JWMSY.CompareService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EasAndWmsCompareReportSoap", Namespace="http://tempuri.org/")]
    public partial class EasAndWmsCompareReport : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPurReceivalDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMoveIssueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMoveInWarehsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMoveMaterialReqOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetManufactureRecOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSaleIssueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSaleOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EasAndWmsCompareReport() {
            this.Url = global::JWMSY.Properties.Settings.Default.JWMSY_CompareService_EasAndWmsCompareReport;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPurReceivalDetailCompletedEventHandler GetPurReceivalDetailCompleted;
        
        /// <remarks/>
        public event GetMoveIssueCompletedEventHandler GetMoveIssueCompleted;
        
        /// <remarks/>
        public event GetMoveInWarehsCompletedEventHandler GetMoveInWarehsCompleted;
        
        /// <remarks/>
        public event GetMoveMaterialReqCompletedEventHandler GetMoveMaterialReqCompleted;
        
        /// <remarks/>
        public event GetManufactureRecCompletedEventHandler GetManufactureRecCompleted;
        
        /// <remarks/>
        public event GetSaleIssueCompletedEventHandler GetSaleIssueCompleted;
        
        /// <remarks/>
        public event GetSaleOrderCompletedEventHandler GetSaleOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPurReceivalDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPurReceivalDetail(System.DateTime dDate) {
            object[] results = this.Invoke("GetPurReceivalDetail", new object[] {
                        dDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPurReceivalDetailAsync(System.DateTime dDate) {
            this.GetPurReceivalDetailAsync(dDate, null);
        }
        
        /// <remarks/>
        public void GetPurReceivalDetailAsync(System.DateTime dDate, object userState) {
            if ((this.GetPurReceivalDetailOperationCompleted == null)) {
                this.GetPurReceivalDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPurReceivalDetailOperationCompleted);
            }
            this.InvokeAsync("GetPurReceivalDetail", new object[] {
                        dDate}, this.GetPurReceivalDetailOperationCompleted, userState);
        }
        
        private void OnGetPurReceivalDetailOperationCompleted(object arg) {
            if ((this.GetPurReceivalDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPurReceivalDetailCompleted(this, new GetPurReceivalDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMoveIssue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMoveIssue(System.DateTime dDate) {
            object[] results = this.Invoke("GetMoveIssue", new object[] {
                        dDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMoveIssueAsync(System.DateTime dDate) {
            this.GetMoveIssueAsync(dDate, null);
        }
        
        /// <remarks/>
        public void GetMoveIssueAsync(System.DateTime dDate, object userState) {
            if ((this.GetMoveIssueOperationCompleted == null)) {
                this.GetMoveIssueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMoveIssueOperationCompleted);
            }
            this.InvokeAsync("GetMoveIssue", new object[] {
                        dDate}, this.GetMoveIssueOperationCompleted, userState);
        }
        
        private void OnGetMoveIssueOperationCompleted(object arg) {
            if ((this.GetMoveIssueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMoveIssueCompleted(this, new GetMoveIssueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMoveInWarehs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMoveInWarehs(System.DateTime dDate) {
            object[] results = this.Invoke("GetMoveInWarehs", new object[] {
                        dDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMoveInWarehsAsync(System.DateTime dDate) {
            this.GetMoveInWarehsAsync(dDate, null);
        }
        
        /// <remarks/>
        public void GetMoveInWarehsAsync(System.DateTime dDate, object userState) {
            if ((this.GetMoveInWarehsOperationCompleted == null)) {
                this.GetMoveInWarehsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMoveInWarehsOperationCompleted);
            }
            this.InvokeAsync("GetMoveInWarehs", new object[] {
                        dDate}, this.GetMoveInWarehsOperationCompleted, userState);
        }
        
        private void OnGetMoveInWarehsOperationCompleted(object arg) {
            if ((this.GetMoveInWarehsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMoveInWarehsCompleted(this, new GetMoveInWarehsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMoveMaterialReq", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMoveMaterialReq(System.DateTime dDate) {
            object[] results = this.Invoke("GetMoveMaterialReq", new object[] {
                        dDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMoveMaterialReqAsync(System.DateTime dDate) {
            this.GetMoveMaterialReqAsync(dDate, null);
        }
        
        /// <remarks/>
        public void GetMoveMaterialReqAsync(System.DateTime dDate, object userState) {
            if ((this.GetMoveMaterialReqOperationCompleted == null)) {
                this.GetMoveMaterialReqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMoveMaterialReqOperationCompleted);
            }
            this.InvokeAsync("GetMoveMaterialReq", new object[] {
                        dDate}, this.GetMoveMaterialReqOperationCompleted, userState);
        }
        
        private void OnGetMoveMaterialReqOperationCompleted(object arg) {
            if ((this.GetMoveMaterialReqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMoveMaterialReqCompleted(this, new GetMoveMaterialReqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetManufactureRec", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetManufactureRec(System.DateTime dDate) {
            object[] results = this.Invoke("GetManufactureRec", new object[] {
                        dDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetManufactureRecAsync(System.DateTime dDate) {
            this.GetManufactureRecAsync(dDate, null);
        }
        
        /// <remarks/>
        public void GetManufactureRecAsync(System.DateTime dDate, object userState) {
            if ((this.GetManufactureRecOperationCompleted == null)) {
                this.GetManufactureRecOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetManufactureRecOperationCompleted);
            }
            this.InvokeAsync("GetManufactureRec", new object[] {
                        dDate}, this.GetManufactureRecOperationCompleted, userState);
        }
        
        private void OnGetManufactureRecOperationCompleted(object arg) {
            if ((this.GetManufactureRecCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetManufactureRecCompleted(this, new GetManufactureRecCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSaleIssue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSaleIssue(System.DateTime dDate) {
            object[] results = this.Invoke("GetSaleIssue", new object[] {
                        dDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSaleIssueAsync(System.DateTime dDate) {
            this.GetSaleIssueAsync(dDate, null);
        }
        
        /// <remarks/>
        public void GetSaleIssueAsync(System.DateTime dDate, object userState) {
            if ((this.GetSaleIssueOperationCompleted == null)) {
                this.GetSaleIssueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSaleIssueOperationCompleted);
            }
            this.InvokeAsync("GetSaleIssue", new object[] {
                        dDate}, this.GetSaleIssueOperationCompleted, userState);
        }
        
        private void OnGetSaleIssueOperationCompleted(object arg) {
            if ((this.GetSaleIssueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSaleIssueCompleted(this, new GetSaleIssueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSaleOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetSaleOrder(System.DateTime dStartDate, System.DateTime dEndDate) {
            object[] results = this.Invoke("GetSaleOrder", new object[] {
                        dStartDate,
                        dEndDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetSaleOrderAsync(System.DateTime dStartDate, System.DateTime dEndDate) {
            this.GetSaleOrderAsync(dStartDate, dEndDate, null);
        }
        
        /// <remarks/>
        public void GetSaleOrderAsync(System.DateTime dStartDate, System.DateTime dEndDate, object userState) {
            if ((this.GetSaleOrderOperationCompleted == null)) {
                this.GetSaleOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSaleOrderOperationCompleted);
            }
            this.InvokeAsync("GetSaleOrder", new object[] {
                        dStartDate,
                        dEndDate}, this.GetSaleOrderOperationCompleted, userState);
        }
        
        private void OnGetSaleOrderOperationCompleted(object arg) {
            if ((this.GetSaleOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSaleOrderCompleted(this, new GetSaleOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetPurReceivalDetailCompletedEventHandler(object sender, GetPurReceivalDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPurReceivalDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPurReceivalDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetMoveIssueCompletedEventHandler(object sender, GetMoveIssueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMoveIssueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMoveIssueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetMoveInWarehsCompletedEventHandler(object sender, GetMoveInWarehsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMoveInWarehsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMoveInWarehsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetMoveMaterialReqCompletedEventHandler(object sender, GetMoveMaterialReqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMoveMaterialReqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMoveMaterialReqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetManufactureRecCompletedEventHandler(object sender, GetManufactureRecCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetManufactureRecCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetManufactureRecCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetSaleIssueCompletedEventHandler(object sender, GetSaleIssueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSaleIssueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSaleIssueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetSaleOrderCompletedEventHandler(object sender, GetSaleOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSaleOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSaleOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591